# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/libs/bits/v1/types.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/libs/bits/v1/types.proto',
  package='cometbft.libs.bits.v1',
  syntax='proto3',
  serialized_options=b'Z6github.com/cometbft/cometbft/api/cometbft/libs/bits/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!cometbft/libs/bits/v1/types.proto\x12\x15\x63ometbft.libs.bits.v1\"\'\n\x08\x42itArray\x12\x0c\n\x04\x62its\x18\x01 \x01(\x03\x12\r\n\x05\x65lems\x18\x02 \x03(\x04\x42\x38Z6github.com/cometbft/cometbft/api/cometbft/libs/bits/v1b\x06proto3'
)




_BITARRAY = _descriptor.Descriptor(
  name='BitArray',
  full_name='cometbft.libs.bits.v1.BitArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bits', full_name='cometbft.libs.bits.v1.BitArray.bits', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elems', full_name='cometbft.libs.bits.v1.BitArray.elems', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['BitArray'] = _BITARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BitArray = _reflection.GeneratedProtocolMessageType('BitArray', (_message.Message,), {
  'DESCRIPTOR' : _BITARRAY,
  '__module__' : 'cometbft.libs.bits.v1.types_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.libs.bits.v1.BitArray)
  })
_sym_db.RegisterMessage(BitArray)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
