# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/types/v1beta1/validator.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cometbft.crypto.v1 import keys_pb2 as cometbft_dot_crypto_dot_v1_dot_keys__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/types/v1beta1/validator.proto',
  package='cometbft.types.v1beta1',
  syntax='proto3',
  serialized_options=b'Z7github.com/cometbft/cometbft/api/cometbft/types/v1beta1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&cometbft/types/v1beta1/validator.proto\x12\x16\x63ometbft.types.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1d\x63ometbft/crypto/v1/keys.proto\"\x96\x01\n\x0cValidatorSet\x12\x35\n\nvalidators\x18\x01 \x03(\x0b\x32!.cometbft.types.v1beta1.Validator\x12\x33\n\x08proposer\x18\x02 \x01(\x0b\x32!.cometbft.types.v1beta1.Validator\x12\x1a\n\x12total_voting_power\x18\x03 \x01(\x03\"\x83\x01\n\tValidator\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x34\n\x07pub_key\x18\x02 \x01(\x0b\x32\x1d.cometbft.crypto.v1.PublicKeyB\x04\xc8\xde\x1f\x00\x12\x14\n\x0cvoting_power\x18\x03 \x01(\x03\x12\x19\n\x11proposer_priority\x18\x04 \x01(\x03\"W\n\x0fSimpleValidator\x12.\n\x07pub_key\x18\x01 \x01(\x0b\x32\x1d.cometbft.crypto.v1.PublicKey\x12\x14\n\x0cvoting_power\x18\x02 \x01(\x03*\xd7\x01\n\x0b\x42lockIDFlag\x12\x31\n\x15\x42LOCK_ID_FLAG_UNKNOWN\x10\x00\x1a\x16\x8a\x9d \x12\x42lockIDFlagUnknown\x12/\n\x14\x42LOCK_ID_FLAG_ABSENT\x10\x01\x1a\x15\x8a\x9d \x11\x42lockIDFlagAbsent\x12/\n\x14\x42LOCK_ID_FLAG_COMMIT\x10\x02\x1a\x15\x8a\x9d \x11\x42lockIDFlagCommit\x12)\n\x11\x42LOCK_ID_FLAG_NIL\x10\x03\x1a\x12\x8a\x9d \x0e\x42lockIDFlagNil\x1a\x08\xa8\xa4\x1e\x01\x88\xa3\x1e\x00\x42\x39Z7github.com/cometbft/cometbft/api/cometbft/types/v1beta1b\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cometbft_dot_crypto_dot_v1_dot_keys__pb2.DESCRIPTOR,])

_BLOCKIDFLAG = _descriptor.EnumDescriptor(
  name='BlockIDFlag',
  full_name='cometbft.types.v1beta1.BlockIDFlag',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLOCK_ID_FLAG_UNKNOWN', index=0, number=0,
      serialized_options=b'\212\235 \022BlockIDFlagUnknown',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_ID_FLAG_ABSENT', index=1, number=1,
      serialized_options=b'\212\235 \021BlockIDFlagAbsent',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_ID_FLAG_COMMIT', index=2, number=2,
      serialized_options=b'\212\235 \021BlockIDFlagCommit',
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_ID_FLAG_NIL', index=3, number=3,
      serialized_options=b'\212\235 \016BlockIDFlagNil',
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=b'\250\244\036\001\210\243\036\000',
  serialized_start=496,
  serialized_end=711,
)
_sym_db.RegisterEnumDescriptor(_BLOCKIDFLAG)

BlockIDFlag = enum_type_wrapper.EnumTypeWrapper(_BLOCKIDFLAG)
BLOCK_ID_FLAG_UNKNOWN = 0
BLOCK_ID_FLAG_ABSENT = 1
BLOCK_ID_FLAG_COMMIT = 2
BLOCK_ID_FLAG_NIL = 3



_VALIDATORSET = _descriptor.Descriptor(
  name='ValidatorSet',
  full_name='cometbft.types.v1beta1.ValidatorSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validators', full_name='cometbft.types.v1beta1.ValidatorSet.validators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proposer', full_name='cometbft.types.v1beta1.ValidatorSet.proposer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_voting_power', full_name='cometbft.types.v1beta1.ValidatorSet.total_voting_power', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=270,
)


_VALIDATOR = _descriptor.Descriptor(
  name='Validator',
  full_name='cometbft.types.v1beta1.Validator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='cometbft.types.v1beta1.Validator.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='cometbft.types.v1beta1.Validator.pub_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voting_power', full_name='cometbft.types.v1beta1.Validator.voting_power', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proposer_priority', full_name='cometbft.types.v1beta1.Validator.proposer_priority', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=404,
)


_SIMPLEVALIDATOR = _descriptor.Descriptor(
  name='SimpleValidator',
  full_name='cometbft.types.v1beta1.SimpleValidator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='cometbft.types.v1beta1.SimpleValidator.pub_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voting_power', full_name='cometbft.types.v1beta1.SimpleValidator.voting_power', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=493,
)

_VALIDATORSET.fields_by_name['validators'].message_type = _VALIDATOR
_VALIDATORSET.fields_by_name['proposer'].message_type = _VALIDATOR
_VALIDATOR.fields_by_name['pub_key'].message_type = cometbft_dot_crypto_dot_v1_dot_keys__pb2._PUBLICKEY
_SIMPLEVALIDATOR.fields_by_name['pub_key'].message_type = cometbft_dot_crypto_dot_v1_dot_keys__pb2._PUBLICKEY
DESCRIPTOR.message_types_by_name['ValidatorSet'] = _VALIDATORSET
DESCRIPTOR.message_types_by_name['Validator'] = _VALIDATOR
DESCRIPTOR.message_types_by_name['SimpleValidator'] = _SIMPLEVALIDATOR
DESCRIPTOR.enum_types_by_name['BlockIDFlag'] = _BLOCKIDFLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValidatorSet = _reflection.GeneratedProtocolMessageType('ValidatorSet', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATORSET,
  '__module__' : 'cometbft.types.v1beta1.validator_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.types.v1beta1.ValidatorSet)
  })
_sym_db.RegisterMessage(ValidatorSet)

Validator = _reflection.GeneratedProtocolMessageType('Validator', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATOR,
  '__module__' : 'cometbft.types.v1beta1.validator_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.types.v1beta1.Validator)
  })
_sym_db.RegisterMessage(Validator)

SimpleValidator = _reflection.GeneratedProtocolMessageType('SimpleValidator', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEVALIDATOR,
  '__module__' : 'cometbft.types.v1beta1.validator_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.types.v1beta1.SimpleValidator)
  })
_sym_db.RegisterMessage(SimpleValidator)


DESCRIPTOR._options = None
_BLOCKIDFLAG._options = None
_BLOCKIDFLAG.values_by_name["BLOCK_ID_FLAG_UNKNOWN"]._options = None
_BLOCKIDFLAG.values_by_name["BLOCK_ID_FLAG_ABSENT"]._options = None
_BLOCKIDFLAG.values_by_name["BLOCK_ID_FLAG_COMMIT"]._options = None
_BLOCKIDFLAG.values_by_name["BLOCK_ID_FLAG_NIL"]._options = None
_VALIDATOR.fields_by_name['pub_key']._options = None
# @@protoc_insertion_point(module_scope)
