# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/services/version/v1/version_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.services.version.v1 import version_pb2 as cometbft_dot_services_dot_version_dot_v1_dot_version__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/services/version/v1/version_service.proto',
  package='cometbft.services.version.v1',
  syntax='proto3',
  serialized_options=b'Z=github.com/cometbft/cometbft/api/cometbft/services/version/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2cometbft/services/version/v1/version_service.proto\x12\x1c\x63ometbft.services.version.v1\x1a*cometbft/services/version/v1/version.proto2\x81\x01\n\x0eVersionService\x12o\n\nGetVersion\x12/.cometbft.services.version.v1.GetVersionRequest\x1a\x30.cometbft.services.version.v1.GetVersionResponseB?Z=github.com/cometbft/cometbft/api/cometbft/services/version/v1b\x06proto3'
  ,
  dependencies=[cometbft_dot_services_dot_version_dot_v1_dot_version__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_VERSIONSERVICE = _descriptor.ServiceDescriptor(
  name='VersionService',
  full_name='cometbft.services.version.v1.VersionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVersion',
    full_name='cometbft.services.version.v1.VersionService.GetVersion',
    index=0,
    containing_service=None,
    input_type=cometbft_dot_services_dot_version_dot_v1_dot_version__pb2._GETVERSIONREQUEST,
    output_type=cometbft_dot_services_dot_version_dot_v1_dot_version__pb2._GETVERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERSIONSERVICE)

DESCRIPTOR.services_by_name['VersionService'] = _VERSIONSERVICE

# @@protoc_insertion_point(module_scope)
