# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/types/v1/events.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/types/v1/events.proto',
  package='cometbft.types.v1',
  syntax='proto3',
  serialized_options=b'Z2github.com/cometbft/cometbft/api/cometbft/types/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ometbft/types/v1/events.proto\x12\x11\x63ometbft.types.v1\"B\n\x13\x45ventDataRoundState\x12\x0e\n\x06height\x18\x01 \x01(\x03\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\tB4Z2github.com/cometbft/cometbft/api/cometbft/types/v1b\x06proto3'
)




_EVENTDATAROUNDSTATE = _descriptor.Descriptor(
  name='EventDataRoundState',
  full_name='cometbft.types.v1.EventDataRoundState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='cometbft.types.v1.EventDataRoundState.height', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='cometbft.types.v1.EventDataRoundState.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='cometbft.types.v1.EventDataRoundState.step', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['EventDataRoundState'] = _EVENTDATAROUNDSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventDataRoundState = _reflection.GeneratedProtocolMessageType('EventDataRoundState', (_message.Message,), {
  'DESCRIPTOR' : _EVENTDATAROUNDSTATE,
  '__module__' : 'cometbft.types.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.types.v1.EventDataRoundState)
  })
_sym_db.RegisterMessage(EventDataRoundState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
