# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/services/block/v1/block_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.services.block.v1 import block_pb2 as cometbft_dot_services_dot_block_dot_v1_dot_block__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/services/block/v1/block_service.proto',
  package='cometbft.services.block.v1',
  syntax='proto3',
  serialized_options=b'Z;github.com/cometbft/cometbft/api/cometbft/services/block/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.cometbft/services/block/v1/block_service.proto\x12\x1a\x63ometbft.services.block.v1\x1a&cometbft/services/block/v1/block.proto2\xfc\x01\n\x0c\x42lockService\x12n\n\x0bGetByHeight\x12..cometbft.services.block.v1.GetByHeightRequest\x1a/.cometbft.services.block.v1.GetByHeightResponse\x12|\n\x0fGetLatestHeight\x12\x32.cometbft.services.block.v1.GetLatestHeightRequest\x1a\x33.cometbft.services.block.v1.GetLatestHeightResponse0\x01\x42=Z;github.com/cometbft/cometbft/api/cometbft/services/block/v1b\x06proto3'
  ,
  dependencies=[cometbft_dot_services_dot_block_dot_v1_dot_block__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_BLOCKSERVICE = _descriptor.ServiceDescriptor(
  name='BlockService',
  full_name='cometbft.services.block.v1.BlockService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=371,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetByHeight',
    full_name='cometbft.services.block.v1.BlockService.GetByHeight',
    index=0,
    containing_service=None,
    input_type=cometbft_dot_services_dot_block_dot_v1_dot_block__pb2._GETBYHEIGHTREQUEST,
    output_type=cometbft_dot_services_dot_block_dot_v1_dot_block__pb2._GETBYHEIGHTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestHeight',
    full_name='cometbft.services.block.v1.BlockService.GetLatestHeight',
    index=1,
    containing_service=None,
    input_type=cometbft_dot_services_dot_block_dot_v1_dot_block__pb2._GETLATESTHEIGHTREQUEST,
    output_type=cometbft_dot_services_dot_block_dot_v1_dot_block__pb2._GETLATESTHEIGHTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKSERVICE)

DESCRIPTOR.services_by_name['BlockService'] = _BLOCKSERVICE

# @@protoc_insertion_point(module_scope)
