# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/p2p/v1/pex.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.p2p.v1 import types_pb2 as cometbft_dot_p2p_dot_v1_dot_types__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/p2p/v1/pex.proto',
  package='cometbft.p2p.v1',
  syntax='proto3',
  serialized_options=b'Z0github.com/cometbft/cometbft/api/cometbft/p2p/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63ometbft/p2p/v1/pex.proto\x12\x0f\x63ometbft.p2p.v1\x1a\x1b\x63ometbft/p2p/v1/types.proto\x1a\x14gogoproto/gogo.proto\"\x0c\n\nPexRequest\"<\n\x08PexAddrs\x12\x30\n\x05\x61\x64\x64rs\x18\x01 \x03(\x0b\x32\x1b.cometbft.p2p.v1.NetAddressB\x04\xc8\xde\x1f\x00\"t\n\x07Message\x12\x32\n\x0bpex_request\x18\x01 \x01(\x0b\x32\x1b.cometbft.p2p.v1.PexRequestH\x00\x12.\n\tpex_addrs\x18\x02 \x01(\x0b\x32\x19.cometbft.p2p.v1.PexAddrsH\x00\x42\x05\n\x03sumB2Z0github.com/cometbft/cometbft/api/cometbft/p2p/v1b\x06proto3'
  ,
  dependencies=[cometbft_dot_p2p_dot_v1_dot_types__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_PEXREQUEST = _descriptor.Descriptor(
  name='PexRequest',
  full_name='cometbft.p2p.v1.PexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=109,
)


_PEXADDRS = _descriptor.Descriptor(
  name='PexAddrs',
  full_name='cometbft.p2p.v1.PexAddrs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addrs', full_name='cometbft.p2p.v1.PexAddrs.addrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=171,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='cometbft.p2p.v1.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pex_request', full_name='cometbft.p2p.v1.Message.pex_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pex_addrs', full_name='cometbft.p2p.v1.Message.pex_addrs', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sum', full_name='cometbft.p2p.v1.Message.sum',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=173,
  serialized_end=289,
)

_PEXADDRS.fields_by_name['addrs'].message_type = cometbft_dot_p2p_dot_v1_dot_types__pb2._NETADDRESS
_MESSAGE.fields_by_name['pex_request'].message_type = _PEXREQUEST
_MESSAGE.fields_by_name['pex_addrs'].message_type = _PEXADDRS
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['pex_request'])
_MESSAGE.fields_by_name['pex_request'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
_MESSAGE.oneofs_by_name['sum'].fields.append(
  _MESSAGE.fields_by_name['pex_addrs'])
_MESSAGE.fields_by_name['pex_addrs'].containing_oneof = _MESSAGE.oneofs_by_name['sum']
DESCRIPTOR.message_types_by_name['PexRequest'] = _PEXREQUEST
DESCRIPTOR.message_types_by_name['PexAddrs'] = _PEXADDRS
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PexRequest = _reflection.GeneratedProtocolMessageType('PexRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEXREQUEST,
  '__module__' : 'cometbft.p2p.v1.pex_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.p2p.v1.PexRequest)
  })
_sym_db.RegisterMessage(PexRequest)

PexAddrs = _reflection.GeneratedProtocolMessageType('PexAddrs', (_message.Message,), {
  'DESCRIPTOR' : _PEXADDRS,
  '__module__' : 'cometbft.p2p.v1.pex_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.p2p.v1.PexAddrs)
  })
_sym_db.RegisterMessage(PexAddrs)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'cometbft.p2p.v1.pex_pb2'
  # @@protoc_insertion_point(class_scope:cometbft.p2p.v1.Message)
  })
_sym_db.RegisterMessage(Message)


DESCRIPTOR._options = None
_PEXADDRS.fields_by_name['addrs']._options = None
# @@protoc_insertion_point(module_scope)
