# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cometbft/abci/v1/service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.abci.v1 import types_pb2 as cometbft_dot_abci_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cometbft/abci/v1/service.proto',
  package='cometbft.abci.v1',
  syntax='proto3',
  serialized_options=b'Z1github.com/cometbft/cometbft/api/cometbft/abci/v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ometbft/abci/v1/service.proto\x12\x10\x63ometbft.abci.v1\x1a\x1c\x63ometbft/abci/v1/types.proto2\xc4\x0b\n\x0b\x41\x42\x43IService\x12\x45\n\x04\x45\x63ho\x12\x1d.cometbft.abci.v1.EchoRequest\x1a\x1e.cometbft.abci.v1.EchoResponse\x12H\n\x05\x46lush\x12\x1e.cometbft.abci.v1.FlushRequest\x1a\x1f.cometbft.abci.v1.FlushResponse\x12\x45\n\x04Info\x12\x1d.cometbft.abci.v1.InfoRequest\x1a\x1e.cometbft.abci.v1.InfoResponse\x12N\n\x07\x43heckTx\x12 .cometbft.abci.v1.CheckTxRequest\x1a!.cometbft.abci.v1.CheckTxResponse\x12H\n\x05Query\x12\x1e.cometbft.abci.v1.QueryRequest\x1a\x1f.cometbft.abci.v1.QueryResponse\x12K\n\x06\x43ommit\x12\x1f.cometbft.abci.v1.CommitRequest\x1a .cometbft.abci.v1.CommitResponse\x12T\n\tInitChain\x12\".cometbft.abci.v1.InitChainRequest\x1a#.cometbft.abci.v1.InitChainResponse\x12`\n\rListSnapshots\x12&.cometbft.abci.v1.ListSnapshotsRequest\x1a\'.cometbft.abci.v1.ListSnapshotsResponse\x12`\n\rOfferSnapshot\x12&.cometbft.abci.v1.OfferSnapshotRequest\x1a\'.cometbft.abci.v1.OfferSnapshotResponse\x12l\n\x11LoadSnapshotChunk\x12*.cometbft.abci.v1.LoadSnapshotChunkRequest\x1a+.cometbft.abci.v1.LoadSnapshotChunkResponse\x12o\n\x12\x41pplySnapshotChunk\x12+.cometbft.abci.v1.ApplySnapshotChunkRequest\x1a,.cometbft.abci.v1.ApplySnapshotChunkResponse\x12\x66\n\x0fPrepareProposal\x12(.cometbft.abci.v1.PrepareProposalRequest\x1a).cometbft.abci.v1.PrepareProposalResponse\x12\x66\n\x0fProcessProposal\x12(.cometbft.abci.v1.ProcessProposalRequest\x1a).cometbft.abci.v1.ProcessProposalResponse\x12W\n\nExtendVote\x12#.cometbft.abci.v1.ExtendVoteRequest\x1a$.cometbft.abci.v1.ExtendVoteResponse\x12r\n\x13VerifyVoteExtension\x12,.cometbft.abci.v1.VerifyVoteExtensionRequest\x1a-.cometbft.abci.v1.VerifyVoteExtensionResponse\x12`\n\rFinalizeBlock\x12&.cometbft.abci.v1.FinalizeBlockRequest\x1a\'.cometbft.abci.v1.FinalizeBlockResponseB3Z1github.com/cometbft/cometbft/api/cometbft/abci/v1b\x06proto3'
  ,
  dependencies=[cometbft_dot_abci_dot_v1_dot_types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ABCISERVICE = _descriptor.ServiceDescriptor(
  name='ABCIService',
  full_name='cometbft.abci.v1.ABCIService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=1559,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='cometbft.abci.v1.ABCIService.Echo',
    index=0,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._ECHOREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._ECHORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Flush',
    full_name='cometbft.abci.v1.ABCIService.Flush',
    index=1,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._FLUSHREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._FLUSHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Info',
    full_name='cometbft.abci.v1.ABCIService.Info',
    index=2,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._INFOREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._INFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckTx',
    full_name='cometbft.abci.v1.ABCIService.CheckTx',
    index=3,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._CHECKTXREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._CHECKTXRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='cometbft.abci.v1.ABCIService.Query',
    index=4,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._QUERYREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Commit',
    full_name='cometbft.abci.v1.ABCIService.Commit',
    index=5,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._COMMITREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._COMMITRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InitChain',
    full_name='cometbft.abci.v1.ABCIService.InitChain',
    index=6,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._INITCHAINREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._INITCHAINRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListSnapshots',
    full_name='cometbft.abci.v1.ABCIService.ListSnapshots',
    index=7,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._LISTSNAPSHOTSREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._LISTSNAPSHOTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OfferSnapshot',
    full_name='cometbft.abci.v1.ABCIService.OfferSnapshot',
    index=8,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._OFFERSNAPSHOTREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._OFFERSNAPSHOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadSnapshotChunk',
    full_name='cometbft.abci.v1.ABCIService.LoadSnapshotChunk',
    index=9,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._LOADSNAPSHOTCHUNKREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._LOADSNAPSHOTCHUNKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ApplySnapshotChunk',
    full_name='cometbft.abci.v1.ABCIService.ApplySnapshotChunk',
    index=10,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._APPLYSNAPSHOTCHUNKREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._APPLYSNAPSHOTCHUNKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PrepareProposal',
    full_name='cometbft.abci.v1.ABCIService.PrepareProposal',
    index=11,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._PREPAREPROPOSALREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._PREPAREPROPOSALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ProcessProposal',
    full_name='cometbft.abci.v1.ABCIService.ProcessProposal',
    index=12,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._PROCESSPROPOSALREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._PROCESSPROPOSALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExtendVote',
    full_name='cometbft.abci.v1.ABCIService.ExtendVote',
    index=13,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._EXTENDVOTEREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._EXTENDVOTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyVoteExtension',
    full_name='cometbft.abci.v1.ABCIService.VerifyVoteExtension',
    index=14,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._VERIFYVOTEEXTENSIONREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._VERIFYVOTEEXTENSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FinalizeBlock',
    full_name='cometbft.abci.v1.ABCIService.FinalizeBlock',
    index=15,
    containing_service=None,
    input_type=cometbft_dot_abci_dot_v1_dot_types__pb2._FINALIZEBLOCKREQUEST,
    output_type=cometbft_dot_abci_dot_v1_dot_types__pb2._FINALIZEBLOCKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ABCISERVICE)

DESCRIPTOR.services_by_name['ABCIService'] = _ABCISERVICE

# @@protoc_insertion_point(module_scope)
